# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [87]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [88]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [89]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[6, 2, 3, 1],
         [8, 8, 9, 9],
         [8, 6, 2, 7]],
 
        [[7, 6, 9, 1],
         [5, 9, 7, 6],
         [9, 2, 4, 8]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [90]:
c[1,2,3]

8

In [91]:
## Arithmetic in arrays is element wise

In [92]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [93]:
c = a-b
c

array([20, 29, 38, 47])

In [94]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [95]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [96]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [97]:
a[2:5]

array([ 4,  9, 16])

In [98]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [99]:
b = np.random.randint(1,100,(4,4))

In [100]:
b

array([[72, 12, 41, 22],
       [93, 97, 11, 55],
       [90, 84, 68, 33],
       [86, 98, 35, 45]])

In [101]:
# Guess the output
print(b[2,3])
print(b[0,0])


33
72


In [102]:
b[0:3,1],b[:,1]

(array([12, 97, 84]), array([12, 97, 84, 98]))

In [103]:
b[1:3,:]

array([[93, 97, 11, 55],
       [90, 84, 68, 33]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [104]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [105]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [106]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [107]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  1.185330  2.907188 -0.991266  0.055786
2014-01-02  0.399082 -0.133242 -0.705072  0.089668
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341
2014-01-04 -1.234861  2.273797  0.878611  0.258666
2014-01-05 -0.840489  2.155845  1.529104  1.667760
2014-01-06 -1.405001  0.152192 -0.437986 -0.147681

In [108]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [109]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [110]:
df.head()

A         B         C         D
2014-01-01  1.185330  2.907188 -0.991266  0.055786
2014-01-02  0.399082 -0.133242 -0.705072  0.089668
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341
2014-01-04 -1.234861  2.273797  0.878611  0.258666
2014-01-05 -0.840489  2.155845  1.529104  1.667760

In [111]:
df.tail()

A         B         C         D
2014-01-02  0.399082 -0.133242 -0.705072  0.089668
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341
2014-01-04 -1.234861  2.273797  0.878611  0.258666
2014-01-05 -0.840489  2.155845  1.529104  1.667760
2014-01-06 -1.405001  0.152192 -0.437986 -0.147681

In [112]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [113]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.360657  1.105563  0.024009  0.517923
std    1.006080  1.516491  0.979281  0.731044
min   -1.405001 -0.722404 -0.991266 -0.147681
25%   -1.136268 -0.061883 -0.638300  0.064257
50%   -0.554247  1.154018 -0.283662  0.174167
75%    0.232310  2.244309  0.626624  0.952172
max    1.185330  2.907188  1.529104  1.667760

In [114]:
df.sort_values(by='B')


A         B         C         D
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341
2014-01-02  0.399082 -0.133242 -0.705072  0.089668
2014-01-06 -1.405001  0.152192 -0.437986 -0.147681
2014-01-05 -0.840489  2.155845  1.529104  1.667760
2014-01-04 -1.234861  2.273797  0.878611  0.258666
2014-01-01  1.185330  2.907188 -0.991266  0.055786

### Selection

In [115]:
df[['A','B']]

A         B
2014-01-01  1.185330  2.907188
2014-01-02  0.399082 -0.133242
2014-01-03 -0.268005 -0.722404
2014-01-04 -1.234861  2.273797
2014-01-05 -0.840489  2.155845
2014-01-06 -1.405001  0.152192

In [116]:
df[0:3]

A         B         C         D
2014-01-01  1.185330  2.907188 -0.991266  0.055786
2014-01-02  0.399082 -0.133242 -0.705072  0.089668
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341

In [117]:
# By label
df.loc[dates[0]]

A    1.185330
B    2.907188
C   -0.991266
D    0.055786
Name: 2014-01-01 00:00:00, dtype: float64

In [118]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  1.185330  2.907188
2014-01-02  0.399082 -0.133242
2014-01-03 -0.268005 -0.722404
2014-01-04 -1.234861  2.273797
2014-01-05 -0.840489  2.155845
2014-01-06 -1.405001  0.152192

In [119]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -0.133242
2014-01-03 -0.722404
2014-01-04  2.273797

In [120]:
# Fast access to scalar
df.at[dates[1],'B']

-0.13324176897839252

In [121]:
# iloc provides integer locations similar to np style
df.iloc[3:,1:2]

B
2014-01-04  2.273797
2014-01-05  2.155845
2014-01-06  0.152192

### Boolean Indexing

In [122]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341
2014-01-04 -1.234861  2.273797  0.878611  0.258666
2014-01-05 -0.840489  2.155845  1.529104  1.667760
2014-01-06 -1.405001  0.152192 -0.437986 -0.147681

### Setting

In [123]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [124]:
df_posA

A         B         C         D
2014-01-01  1.185330  2.907188 -0.991266  0.055786
2014-01-02  0.399082 -0.133242 -0.705072  0.089668
2014-01-03  0.268005  0.722404  0.129339 -1.183341
2014-01-04  1.234861 -2.273797 -0.878611 -0.258666
2014-01-05  0.840489 -2.155845 -1.529104 -1.667760
2014-01-06  1.405001 -0.152192  0.437986  0.147681

In [125]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [126]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [127]:
df['F'] = s1

In [128]:
df

A         B         C         D    F
2014-01-01  1.185330  2.907188 -0.991266  0.055786  NaN
2014-01-02  0.399082 -0.133242 -0.705072  0.089668  1.0
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341  2.0
2014-01-04 -1.234861  2.273797  0.878611  0.258666  3.0
2014-01-05 -0.840489  2.155845  1.529104  1.667760  4.0
2014-01-06 -1.405001  0.152192 -0.437986 -0.147681  5.0

### Missing Data

In [129]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [130]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [131]:
df1

A         B         C         D    F    E
2014-01-01  1.185330  2.907188 -0.991266  0.055786  NaN  1.0
2014-01-02  0.399082 -0.133242 -0.705072  0.089668  1.0  1.0
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341  2.0  NaN
2014-01-04 -1.234861  2.273797  0.878611  0.258666  3.0  NaN

In [132]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [133]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.360657  1.105563  0.024009  0.517923  3.000000
std    1.006080  1.516491  0.979281  0.731044  1.581139
min   -1.405001 -0.722404 -0.991266 -0.147681  1.000000
25%   -1.136268 -0.061883 -0.638300  0.064257       NaN
50%   -0.554247  1.154018 -0.283662  0.174167       NaN
75%    0.232310  2.244309  0.626624  0.952172       NaN
max    1.185330  2.907188  1.529104  1.667760  5.000000

In [134]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.360657
 B    1.105563
 C    0.024009
 D    0.517923
 F    3.000000
 dtype: float64, 2014-01-01    0.789260
 2014-01-02    0.130087
 2014-01-03    0.412719
 2014-01-04    1.035243
 2014-01-05    1.702444
 2014-01-06    0.632305
 Freq: D, dtype: float64)

### Applying functions

In [135]:
df.head()

A         B         C         D    F
2014-01-01  1.185330  2.907188 -0.991266  0.055786  NaN
2014-01-02  0.399082 -0.133242 -0.705072  0.089668  1.0
2014-01-03 -0.268005 -0.722404 -0.129339  1.183341  2.0
2014-01-04 -1.234861  2.273797  0.878611  0.258666  3.0
2014-01-05 -0.840489  2.155845  1.529104  1.667760  4.0

In [136]:
df.apply(np.cumsum).head()

A         B         C         D     F
2014-01-01  1.185330  2.907188 -0.991266  0.055786   NaN
2014-01-02  1.584412  2.773946 -1.696338  0.145454   1.0
2014-01-03  1.316407  2.051542 -1.825677  1.328795   3.0
2014-01-04  0.081546  4.325340 -0.947065  1.587461   6.0
2014-01-05 -0.758942  6.481184  0.582039  3.255222  10.0

In [137]:
def f(x):
    return x.max() - x.min()    # to show the lambda function......

df.apply(lambda x: x.max() - x.min())

A    2.590331
B    3.629592
C    2.520370
D    1.815442
F    4.000000
dtype: float64

In [138]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [139]:

np.random.randn(10,4)

array([[ -8.58536453e-01,   4.25486103e-01,   3.83481361e-01,
          2.49082986e-01],
       [ -2.02049565e+00,  -1.22535440e+00,   1.60022222e+00,
         -1.28183655e+00],
       [ -3.02849468e-01,  -1.63720221e+00,   3.29040057e-02,
         -2.25035202e-01],
       [  2.29687674e-01,  -1.11511170e+00,   1.28141052e+00,
         -7.32391088e-01],
       [ -4.82091697e-02,  -1.67068798e+00,  -1.92684280e+00,
          7.01097478e-01],
       [ -1.97885833e+00,   5.99459389e-02,   7.87588587e-01,
          8.05562406e-01],
       [ -1.50825428e+00,   9.78671287e-01,   8.11839580e-01,
         -1.06164476e+00],
       [  1.31448596e+00,   1.31935854e+00,  -4.50170372e-01,
          7.79436172e-01],
       [ -1.71272350e-03,  -4.01823922e-01,   2.07090424e+00,
          2.84523503e-01],
       [ -4.07877174e-01,   5.49456082e-01,   1.18025518e+00,
          6.14815425e-01]])

In [140]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -1.127950  0.631767 -0.098397 -0.138241
1  0.609628 -0.718920 -0.532113 -1.365048
2  0.130207 -1.580465 -1.324341  0.110339
3 -1.673780 -1.724826 -0.576482  0.257282
4 -0.284489 -0.648289 -0.852096 -0.037499
5 -2.049845 -0.137367  0.528053  0.349155
6  0.061764 -2.065071 -0.116330 -0.402842
7  0.166980 -0.357036  0.963404 -0.511424
8 -1.831619 -0.081777 -0.341107  0.696407
9 -0.375618 -0.922881 -0.589260  0.397489

In [141]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -1.127950  0.631767 -0.098397 -0.138241
 1  0.609628 -0.718920 -0.532113 -1.365048
 2  0.130207 -1.580465 -1.324341  0.110339,
           0         1         2         3
 3 -1.673780 -1.724826 -0.576482  0.257282
 4 -0.284489 -0.648289 -0.852096 -0.037499
 5 -2.049845 -0.137367  0.528053  0.349155
 6  0.061764 -2.065071 -0.116330 -0.402842,
           0         1         2         3
 7  0.166980 -0.357036  0.963404 -0.511424
 8 -1.831619 -0.081777 -0.341107  0.696407
 9 -0.375618 -0.922881 -0.589260  0.397489]

In [142]:
pd.concat(pieces)

0         1         2         3
0 -1.127950  0.631767 -0.098397 -0.138241
1  0.609628 -0.718920 -0.532113 -1.365048
2  0.130207 -1.580465 -1.324341  0.110339
3 -1.673780 -1.724826 -0.576482  0.257282
4 -0.284489 -0.648289 -0.852096 -0.037499
5 -2.049845 -0.137367  0.528053  0.349155
6  0.061764 -2.065071 -0.116330 -0.402842
7  0.166980 -0.357036  0.963404 -0.511424
8 -1.831619 -0.081777 -0.341107  0.696407
9 -0.375618 -0.922881 -0.589260  0.397489

In [143]:
# Also can "Join" and "Append"
df.join

<bound method DataFrame.join of           0         1         2         3
0 -1.127950  0.631767 -0.098397 -0.138241
1  0.609628 -0.718920 -0.532113 -1.365048
2  0.130207 -1.580465 -1.324341  0.110339
3 -1.673780 -1.724826 -0.576482  0.257282
4 -0.284489 -0.648289 -0.852096 -0.037499
5 -2.049845 -0.137367  0.528053  0.349155
6  0.061764 -2.065071 -0.116330 -0.402842
7  0.166980 -0.357036  0.963404 -0.511424
8 -1.831619 -0.081777 -0.341107  0.696407
9 -0.375618 -0.922881 -0.589260  0.397489>

### Grouping


In [144]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [145]:
df

A      B         C         D
0  foo    one -0.857371  0.899541
1  bar    one -0.168261 -0.587375
2  foo    two  0.612105  0.432481
3  bar  three -0.896220  0.672205
4  foo    two -0.746878 -1.236044
5  bar    two  0.129330 -0.871866
6  foo    one  1.045534  1.150339
7  foo  three -0.606717  0.341405

In [146]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -0.168261 -0.587375
    three -0.896220  0.672205
    two    0.129330 -0.871866
foo one    0.188163  2.049880
    three -0.606717  0.341405
    two   -0.134773 -0.803563

### Reshaping

In [147]:
# You can also stack or unstack levels

In [148]:
a = df.groupby(['A','B']).sum()

In [149]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar -0.168261 -0.896220  0.129330 -0.587375  0.672205 -0.871866
foo  0.094081 -0.606717 -0.067386  1.024940  0.341405 -0.401782

### Time Series


In [150]:
import pandas as pd
import numpy as np

In [151]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [152]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [153]:
ts

2014-01-01 00:00:00    322
2014-01-01 00:00:01    169
2014-01-01 00:00:02    327
2014-01-01 00:00:03    420
2014-01-01 00:00:04    324
2014-01-01 00:00:05    345
2014-01-01 00:00:06    218
2014-01-01 00:00:07    238
2014-01-01 00:00:08     73
2014-01-01 00:00:09    308
2014-01-01 00:00:10    378
2014-01-01 00:00:11    262
2014-01-01 00:00:12    153
2014-01-01 00:00:13    228
2014-01-01 00:00:14    395
2014-01-01 00:00:15    116
2014-01-01 00:00:16    328
2014-01-01 00:00:17    259
2014-01-01 00:00:18     80
2014-01-01 00:00:19    164
2014-01-01 00:00:20    153
2014-01-01 00:00:21    481
2014-01-01 00:00:22    267
2014-01-01 00:00:23     64
2014-01-01 00:00:24    341
2014-01-01 00:00:25     66
2014-01-01 00:00:26     82
2014-01-01 00:00:27    239
2014-01-01 00:00:28    220
2014-01-01 00:00:29    126
                      ... 
2014-01-01 00:01:10    176
2014-01-01 00:01:11    445
2014-01-01 00:01:12    452
2014-01-01 00:01:13    171
2014-01-01 00:01:14     10
2014-01-01 00:01:15    291
2

In [154]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    245.033333
2014-01-01 00:01:00    231.950000
Freq: T, dtype: float64

In [155]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-155-5c9240a56f62>, line 2)

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas